services:
  web:
    build:
      context: .
      dockerfile: betting_bot/Docker/Dockerfile
    container_name: bet-bot-web
<<<<<<< HEAD
    command: gunicorn betting_bot.betting_bot.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
=======
    command: gunicorn betting_bot.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/betting_bot
>>>>>>> 534348e (Fix docker + django imports, gunicorn, static files)
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: bet-bot-db
    environment:
      POSTGRES_DB: betbot
      POSTGRES_USER: betbot
      POSTGRES_PASSWORD: betbot
<<<<<<< HEAD
=======
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:

>>>>>>> 534348e (Fix docker + django imports, gunicorn, static files)
