version: "3.9"

services:
  web:
    build: .
    container_name: bet_web
    command: gunicorn betting_bot.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "9000:8000"
    restart: always

  odds_worker:
    build: .
    container_name: bet_odds_worker
    command: python manage.py fetch_odds
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  telegram_bot:
    build: .
    container_name: bet_telegram_bot
    command: python manage.py run_telegram_bot
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
